# Generated by Django 3.2.25 on 2026-03-23 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashIncasso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='сумма')),
                ('happened_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата')),
                ('method', models.CharField(choices=[('cash', 'Наличные'), ('mkassa', 'Банк1'), ('zadatok', 'Задаток'), ('optima', 'Банк2')], default='cash', max_length=12, verbose_name='с какого счета')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incasso_created', to=settings.AUTH_USER_MODEL, verbose_name='создал')),
            ],
            options={
                'verbose_name': 'Инкассация',
                'verbose_name_plural': 'Инкассации',
                'ordering': ['-happened_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Наличные (касса)')),
                ('mkassa_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Mkassa')),
                ('zadatok_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Задаток')),
                ('optima_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Оптима')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Касса',
                'verbose_name_plural': 'Кассы',
                'ordering': ['hotel__name'],
            },
        ),
        migrations.CreateModel(
            name='DDSArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], max_length=10, verbose_name='Вид')),
                ('name', models.CharField(max_length=120, verbose_name='имя')),
                ('is_active', models.BooleanField(default=True, verbose_name='активно?')),
            ],
            options={
                'verbose_name': 'Статья ДДС',
                'verbose_name_plural': 'Статьи ДДС',
                'ordering': ['kind', 'category_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Точка',
                'verbose_name_plural': 'Точки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DDSOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='сумма')),
                ('happened_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата')),
                ('method', models.CharField(choices=[('cash', 'Наличные'), ('mkassa', 'Банк1'), ('zadatok', 'Задаток'), ('optima', 'Банк2')], default='cash', max_length=12, verbose_name='способ оплаты')),
                ('counterparty', models.CharField(blank=True, max_length=180, verbose_name='поставщик/гость/компания')),
                ('comment', models.TextField(blank=True, verbose_name='комментарии')),
                ('source', models.CharField(blank=True, max_length=120, verbose_name='источник')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_voided', models.BooleanField(default=False)),
                ('void_reason', models.CharField(blank=True, max_length=255)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ops', to='dds.ddsarticle', verbose_name='статья')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dds_created', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dds_ops', to='dds.point', verbose_name='точка')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dds_voided', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Операция ДДС',
                'verbose_name_plural': 'Операции ДДС',
                'ordering': ['-happened_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DDSCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход')], max_length=10, verbose_name='Вид')),
                ('name', models.CharField(max_length=120, verbose_name='Категория')),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='dds.ddscategory', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория ДДС',
                'verbose_name_plural': 'Категории ДДС',
                'ordering': ['kind', 'parent_id', 'name'],
            },
        ),
        migrations.AddField(
            model_name='ddsarticle',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='dds.ddscategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='ddsarticle',
            name='hotels',
            field=models.ManyToManyField(blank=True, help_text='Если не выбрать ничего — статья будет доступна во всех точках.', related_name='dds_articles', to='dds.Point', verbose_name='Точки (где доступна статья)'),
        ),
        migrations.CreateModel(
            name='CashTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_account', models.CharField(choices=[('cash', 'Наличные'), ('mkassa', 'Банк1'), ('zadatok', 'Задаток'), ('optima', 'Банк2')], max_length=10, verbose_name='Со счета')),
                ('to_account', models.CharField(choices=[('cash', 'Наличные'), ('mkassa', 'Банк1'), ('zadatok', 'Задаток'), ('optima', 'Банк2')], max_length=10, verbose_name='На счет')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('happened_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_voided', models.BooleanField(default=False)),
                ('void_reason', models.CharField(blank=True, max_length=255)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_transfers_created', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_transfers', to='dds.point', verbose_name='Точка')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='dds.cashregister', verbose_name='Касса')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_transfers_voided', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Перевод между счетами',
                'verbose_name_plural': 'Переводы между счетами',
                'ordering': ['-happened_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='cashregister',
            name='hotel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cash_register', to='dds.point', verbose_name='точка'),
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Приход'), ('out', 'Расход/Списание')], max_length=3)),
                ('account', models.CharField(choices=[('cash', 'Наличные'), ('mkassa', 'Банк1'), ('zadatok', 'Задаток'), ('optima', 'Банк2')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('happened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_moves_created', to=settings.AUTH_USER_MODEL)),
                ('dds_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_moves', to='dds.ddsoperation')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements', to='dds.point')),
                ('incasso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_moves', to='dds.cashincasso')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='dds.cashregister')),
                ('transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='dds.cashtransfer', verbose_name='Перевод')),
            ],
            options={
                'verbose_name': 'Движение денег',
                'verbose_name_plural': 'Движения денег',
                'ordering': ['-happened_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='cashincasso',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incassos', to='dds.point', verbose_name='точка'),
        ),
        migrations.AddIndex(
            model_name='ddsoperation',
            index=models.Index(fields=['hotel', 'happened_at'], name='dds_ddsoper_hotel_i_6b72ae_idx'),
        ),
        migrations.AddIndex(
            model_name='ddsoperation',
            index=models.Index(fields=['article', 'happened_at'], name='dds_ddsoper_article_1d5d95_idx'),
        ),
        migrations.AddConstraint(
            model_name='ddscategory',
            constraint=models.UniqueConstraint(fields=('kind', 'parent', 'name'), name='uniq_dds_category_kind_parent_name'),
        ),
        migrations.AddConstraint(
            model_name='ddsarticle',
            constraint=models.UniqueConstraint(fields=('kind', 'category', 'name'), name='uniq_dds_article_kind_cat_name'),
        ),
        migrations.AddIndex(
            model_name='cashtransfer',
            index=models.Index(fields=['hotel', 'happened_at'], name='dds_cashtra_hotel_i_f361ea_idx'),
        ),
        migrations.AddConstraint(
            model_name='cashmovement',
            constraint=models.UniqueConstraint(condition=models.Q(('dds_operation__isnull', False)), fields=('dds_operation', 'account', 'direction'), name='uniq_cashmove_dds_account_dir'),
        ),
    ]
