# Generated by Django 3.2.25 on 2026-04-20 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Номер телефона')),
                ('whatsapp', models.CharField(blank=True, max_length=30, verbose_name='WhatsApp')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Должность')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='dds.point', verbose_name='Точка')),
            ],
            options={
                'verbose_name': 'Контакт точки',
                'verbose_name_plural': 'Контакты точки',
                'ordering': ['name'],
            },
        ),
    ]
