# Generated by Django 3.2.25 on 2026-04-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tg_chat_id',
            field=models.CharField(blank=True, help_text='Получите у бота командой /start', max_length=50, verbose_name='Telegram Chat ID'),
        ),
    ]
