# Generated by Django 3.2.25 on 2026-04-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_tg_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tg_link_token',
            field=models.CharField(blank=True, max_length=36, verbose_name='Токен привязки TG'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tg_chat_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telegram Chat ID'),
        ),
    ]
